# Generated by Django 4.1.6 on 2023-02-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("banksite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="receiver",
                to="banksite.account",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sender",
                to="banksite.account",
            ),
        ),
    ]
